### ISSUE TITLE
如何能对整个文件夹打包批量下载？

### ISSUE THREAD

**Issue by Nevidebla** [tjsky/pikpak#10]

**Comment by tjsky** [comment]
如果你指的是，勾选文件夹后，可以下载一个文件夹的压缩包的话。那目前是不支持的。

这个功能实际意义不是非常大，
因为pikpak本身后端不支持功能，
只能通过前端流式传输压缩，或者中间服务器压缩，来实现的文件夹打包批量下载

但这样的打包下载过程是：一个一个去请求单个文件下载，只不过增加在本地（通过前端流式传输压缩）或者服务器（中间服务器压缩）一边下载一边压缩的步骤，最后给用户生成为一个压缩包，而不是一个文件夹。

那还不如，使用aria2直接下载文件夹，最后得到一个文件夹。

**Comment by missing233** [comment]
> 如果你指的是，勾选文件夹后，可以下载一个文件夹的压缩包的话。那目前是不支持的。
> 
> 这个功能实际意义不是非常大， 因为pikpak本身后端不支持功能， 只能通过前端流式传输压缩，或者中间服务器压缩，来实现的文件夹打包批量下载
> 
> 但这样的打包下载过程是：一个一个去请求单个文件下载，只不过增加在本地（通过前端流式传输压缩）或者服务器（中间服务器压缩）一边下载一边压缩的步骤，最后给用户生成为一个压缩包，而不是一个文件夹。
> 
> 那还不如，使用aria2直接下载文件夹，最后得到一个文件夹。

目前似乎并不能直接将整个文件夹推送到aria2

**Comment by Nevidebla** [comment]
我知道pikpak服务器后端不支持整个文件夹批量下载，但是这个功能完全可以在前端实现呀，无非就是建立一个任务列表，然后一个个下载呗。有时候获取到的资源就是没有压缩的大量文件，如果挨个手动点击下载要累死人。

**Comment by Nevidebla** [comment]
> 如果你指的是，勾选文件夹后，可以下载一个文件夹的压缩包的话。那目前是不支持的。
> 
> 这个功能实际意义不是非常大， 因为pikpak本身后端不支持功能， 只能通过前端流式传输压缩，或者中间服务器压缩，来实现的文件夹打包批量下载
> 
> 但这样的打包下载过程是：一个一个去请求单个文件下载，只不过增加在本地（通过前端流式传输压缩）或者服务器（中间服务器压缩）一边下载一边压缩的步骤，最后给用户生成为一个压缩包，而不是一个文件夹。
> 
> 那还不如，使用aria2直接下载文件夹，最后得到一个文件夹。

我可能没表述清楚，我的意思就是想要一键下载整个文件夹，包括里面所有文件，而不是一个个文件挨个手动点击。

**Comment by tjsky** [comment]
这个是已经实现了的，在设置的aria2设置部分，开启【选择文件夹时保存文件结构】
![_20221218104150](https://user-images.githubusercontent.com/7272911/208278769-b47dcd72-7171-483f-bf77-9b094e4ea32e.png)
然后在文件列表页，勾选文件夹，在弹出的浮动窗口中，点击【A】图标，推送aria2时，就会保存整个文件夹下所有内容了
![_20221218104329](https://user-images.githubusercontent.com/7272911/208278822-fc43f851-430a-4774-934b-16fcf8911dcf.png)
PS：建议aria2同时下载线程选择为1或者2，太高的同时下载线程可能会出错
